/*
 * Code Screenshot themes (original palettes with made-up names) and the Prism token → role mapping.

 *
 * Roles: fg comment keyword string number func type op punct tag attr prop regex var const
 * Chrome: bg (window), title (file name), gutter (line numbers), hl (highlighted line), border.
 */
const dark = (o) => ({
  dark: true,
  border: "rgba(255,255,255,0.08)",
  hl: "rgba(255,255,255,0.07)",
  ...o,
});
const light = (o) => ({
  dark: false,
  border: "rgba(0,0,0,0.08)",
  hl: "rgba(0,0,0,0.055)",
  ...o,
});

export const THEMES = {
  midnight: dark({
    name: "Midnight",
    bg: "#14161f",
    fg: "#d6deeb",
    title: "#8a93a8",
    gutter: "#4b5263",
    comment: "#6b7489",
    keyword: "#c792ea",
    string: "#addb67",
    number: "#f78c6c",
    func: "#82aaff",
    type: "#ffcb6b",
    op: "#89ddff",
    punct: "#a6accd",
    tag: "#f07178",
    attr: "#ffcb6b",
    prop: "#80cbc4",
    regex: "#5ca7e4",
    var: "#d6deeb",
    const: "#ff5874",
  }),
  ember: dark({
    name: "Ember",
    bg: "#1e1714",
    fg: "#eadbcf",
    title: "#a28e80",
    gutter: "#5c4b40",
    comment: "#7f6a5c",
    keyword: "#ff7a59",
    string: "#e8c27a",
    number: "#f6a85b",
    func: "#ffd28a",
    type: "#f2a07b",
    op: "#ff9e7a",
    punct: "#bfa797",
    tag: "#ff7a59",
    attr: "#e8c27a",
    prop: "#f2c9a8",
    regex: "#d6a36b",
    var: "#eadbcf",
    const: "#ff9f6b",
  }),
  forest: dark({
    name: "Forest",
    bg: "#131b17",
    fg: "#d3e4d7",
    title: "#87a091",
    gutter: "#41544a",
    comment: "#5f7a6b",
    keyword: "#7fd1a8",
    string: "#d9e6a1",
    number: "#f2b880",
    func: "#8fd3e8",
    type: "#c6e38b",
    op: "#9fe0c0",
    punct: "#9bb5a6",
    tag: "#7fd1a8",
    attr: "#d9e6a1",
    prop: "#a7d8c0",
    regex: "#e3c07e",
    var: "#d3e4d7",
    const: "#f2b880",
  }),
  synth: dark({
    name: "Synth",
    bg: "#1b1530",
    fg: "#f1e9ff",
    title: "#9c8cc4",
    gutter: "#4e4373",
    comment: "#7a6ca8",
    keyword: "#ff5fc7",
    string: "#ffe36e",
    number: "#fe9f5d",
    func: "#36f9f6",
    type: "#fe4f8b",
    op: "#ff8bd8",
    punct: "#c3b5ec",
    tag: "#72f1b8",
    attr: "#fede5d",
    prop: "#36f9f6",
    regex: "#ffe36e",
    var: "#f1e9ff",
    const: "#f97e72",
  }),
  graphite: dark({
    name: "Graphite",
    bg: "#1c1c1e",
    fg: "#e5e5e7",
    title: "#98989d",
    gutter: "#545458",
    comment: "#7c7c82",
    keyword: "#ff7ab2",
    string: "#ff8170",
    number: "#d9c97c",
    func: "#67b7a4",
    type: "#5dd8ff",
    op: "#e5e5e7",
    punct: "#a5a5aa",
    tag: "#ff7ab2",
    attr: "#d9c97c",
    prop: "#67b7a4",
    regex: "#ff8170",
    var: "#e5e5e7",
    const: "#d0a8ff",
  }),
  ocean: dark({
    name: "Deep Sea",
    bg: "#0f1d2b",
    fg: "#cfe3f2",
    title: "#7f9bb3",
    gutter: "#3a5368",
    comment: "#5d7a93",
    keyword: "#5ccfe6",
    string: "#bae67e",
    number: "#ffae57",
    func: "#ffd580",
    type: "#73d0ff",
    op: "#f29e74",
    punct: "#8aa4ba",
    tag: "#5ccfe6",
    attr: "#ffd580",
    prop: "#95e6cb",
    regex: "#95e6cb",
    var: "#cfe3f2",
    const: "#d4bfff",
  }),
  paper: light({
    name: "Paper",
    bg: "#ffffff",
    fg: "#24292f",
    title: "#6e7781",
    gutter: "#a0a7b0",
    comment: "#6e7781",
    keyword: "#cf222e",
    string: "#0a3069",
    number: "#0550ae",
    func: "#8250df",
    type: "#953800",
    op: "#0550ae",
    punct: "#57606a",
    tag: "#116329",
    attr: "#0550ae",
    prop: "#0550ae",
    regex: "#116329",
    var: "#24292f",
    const: "#0550ae",
  }),
  sand: light({
    name: "Sand",
    bg: "#fbf6ec",
    fg: "#433a2f",
    title: "#8c7f6b",
    gutter: "#bdb19b",
    comment: "#9a8c74",
    keyword: "#a3448d",
    string: "#4f7a28",
    number: "#b05a1c",
    func: "#2f6db5",
    type: "#9c5f00",
    op: "#7a5c3a",
    punct: "#7a6e5c",
    tag: "#a3448d",
    attr: "#9c5f00",
    prop: "#2f6db5",
    regex: "#4f7a28",
    var: "#433a2f",
    const: "#b05a1c",
  }),
  mint: light({
    name: "Mint",
    bg: "#f2fbf7",
    fg: "#1f3a33",
    title: "#6c8a80",
    gutter: "#a6c2b8",
    comment: "#7d9a90",
    keyword: "#0f7d6b",
    string: "#a14f1d",
    number: "#7a3fb5",
    func: "#1f63c6",
    type: "#0f7d6b",
    op: "#3b6f62",
    punct: "#58756c",
    tag: "#0f7d6b",
    attr: "#a14f1d",
    prop: "#1f63c6",
    regex: "#a14f1d",
    var: "#1f3a33",
    const: "#7a3fb5",
  }),
};

/** Prism token types (and aliases) → theme role, checked from the innermost token outwards. */
const ROLE = {
  comment: "comment",
  prolog: "comment",
  doctype: "comment",
  cdata: "comment",
  keyword: "keyword",
  atrule: "keyword",
  rule: "keyword",
  important: "keyword",
  "control-flow": "keyword",
  module: "keyword",
  string: "string",
  char: "string",
  "template-string": "string",
  "attr-value": "string",
  inserted: "string",
  url: "string",
  number: "number",
  boolean: "const",
  constant: "const",
  symbol: "const",
  null: "const",
  nil: "const",
  deleted: "tag",
  function: "func",
  "function-variable": "func",
  method: "func",
  macro: "func",
  decorator: "func",
  annotation: "func",
  "class-name": "type",
  builtin: "type",
  "maybe-class-name": "type",
  namespace: "type",
  selector: "type",
  operator: "op",
  entity: "op",
  arrow: "op",
  punctuation: "punct",
  tag: "tag",
  "attr-name": "attr",
  property: "prop",
  key: "prop",
  parameter: "var",
  regex: "regex",
  variable: "var",
  interpolation: "var",
};

export function roleOf(types) {
  for (let i = types.length - 1; i >= 0; i--)
    if (ROLE[types[i]]) return ROLE[types[i]];
  return "fg";
}

/** Flatten Prism's nested token stream into [{ text, role }] lines. */
export function toLines(tokens) {
  const lines = [[]];
  const push = (text, role) => {
    const parts = text.split("\n");
    parts.forEach((p, i) => {
      if (i > 0) lines.push([]);
      if (p) lines[lines.length - 1].push({ text: p, role });
    });
  };
  const walk = (tok, stack) => {
    if (typeof tok === "string") return push(tok, roleOf(stack));
    if (Array.isArray(tok)) return tok.forEach((t) => walk(t, stack));
    const types = [
      ...stack,
      tok.type,
      ...(Array.isArray(tok.alias) ? tok.alias : tok.alias ? [tok.alias] : []),
    ];
    walk(tok.content, types);
  };
  walk(tokens, []);
  return lines;
}
