/* Common patterns for the library menu. Samples use reserved example domains and made-up names. */
export const PATTERNS = [
  { group: 'Web', name: 'Email address', pattern: String.raw`[\w.%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}`, flags: 'g',
    sample: 'Write to ada.lovelace@example.com or team+news@mail.example.org.\nNot valid: @example.com, ada@, ada@example' },
  { group: 'Web', name: 'URL (http/https)', pattern: String.raw`https?:\/\/(?:[\w-]+\.)+[a-z]{2,63}(?::\d{2,5})?(?:\/[^\s"'<>]*)?`, flags: 'gi',
    sample: 'Docs at https://docs.example.com/guide?page=2#intro and http://example.org:8080/a/b.\nftp://example.net is not matched.' },
  { group: 'Web', name: 'Domain name', pattern: String.raw`\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}\b`, flags: 'gi',
    sample: 'Hosts: example.com, api.v2.example.org, my-site.example.net' },
  { group: 'Web', name: 'IPv4 address', pattern: String.raw`\b(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\b`, flags: 'g',
    sample: 'Gateway 192.168.0.1, DNS 10.0.0.53, broadcast 255.255.255.255.\nInvalid: 256.1.1.1, 1.2.3' },
  { group: 'Web', name: 'IPv6 address', pattern: String.raw`(?:[\da-f]{1,4}:){7}[\da-f]{1,4}|(?:[\da-f]{1,4}:){1,7}:(?:[\da-f]{1,4}(?::[\da-f]{1,4}){0,5})?|::(?:[\da-f]{1,4}(?::[\da-f]{1,4}){0,6})?`, flags: 'gi',
    sample: 'Full 2001:0db8:85a3:0000:0000:8a2e:0370:7334\nShort 2001:db8::1 and loopback ::1' },
  { group: 'Web', name: 'HTML tag', pattern: String.raw`<\/?([a-z][a-z0-9-]*)\b[^>]*>`, flags: 'gi',
    sample: '<p class="lead">Hello <strong>world</strong></p>\n<img src="cat.png" alt="">' },
  { group: 'Web', name: 'Markdown link', pattern: String.raw`\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)`, flags: 'g',
    sample: 'See [the guide](https://example.com/guide "Guide") or [home](/).' },
  { group: 'Web', name: 'Hex color', pattern: String.raw`#(?:[\da-f]{3,4}){1,2}\b`, flags: 'gi',
    sample: 'color: #0071e3; background: #FFF; border-color: #1d1d1f80;\nNot colors: #12, #ggg' },
  { group: 'Web', name: 'Slug', pattern: String.raw`^[a-z0-9]+(?:-[a-z0-9]+)*$`, flags: 'gm',
    sample: 'my-first-post\nhello-world-2\nNot-A-Slug\ntrailing-' },

  { group: 'Numbers & IDs', name: 'Phone number', pattern: String.raw`(?:\+\d{1,3}[\s.-]?)?\(?\d{2,4}\)?[\s.-]?\d{3,4}[\s.-]?\d{3,4}`, flags: 'g',
    sample: 'Call (555) 010-4477, +1 555 010 4477 or +44 20 7946 0958.' },
  { group: 'Numbers & IDs', name: 'Number (int, decimal, exponent)', pattern: String.raw`[-+]?(?:\d+\.?\d*|\.\d+)(?:e[-+]?\d+)?`, flags: 'gi',
    sample: 'Values: 42, -3.14, .5, +6.02e23, 1e-9' },
  { group: 'Numbers & IDs', name: 'UUID', pattern: String.raw`\b[\da-f]{8}-[\da-f]{4}-[1-8][\da-f]{3}-[89ab][\da-f]{3}-[\da-f]{12}\b`, flags: 'gi',
    sample: 'id: 3f2b8c1e-9d4a-4c6b-8e2f-1a7d9c0b5e44\nv7: 0190f5a2-7c3e-7b1d-9a4f-2e6c8d0b1a35' },
  { group: 'Numbers & IDs', name: 'Semantic version', pattern: String.raw`\bv?(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<pre>[\da-z-]+(?:\.[\da-z-]+)*))?(?:\+(?<build>[\da-z-]+(?:\.[\da-z-]+)*))?\b`, flags: 'gi',
    sample: 'Released v1.4.2, then 2.0.0-beta.3+build.17. Not semver: 1.2, 01.2.3' },
  { group: 'Numbers & IDs', name: 'Card-like number (4×4 digits)', pattern: String.raw`\b(?:\d{4}[ -]?){3}\d{4}\b`, flags: 'g',
    sample: 'Test numbers: 4000 0000 0000 0002, 5555-5555-5555-4444, 4111111111111111' },
  { group: 'Numbers & IDs', name: 'US ZIP code', pattern: String.raw`\b\d{5}(?:-\d{4})?\b`, flags: 'g',
    sample: 'Springfield 01101, Shelbyville 01102-3344' },
  { group: 'Numbers & IDs', name: 'MAC address', pattern: String.raw`\b(?:[\da-f]{2}[:-]){5}[\da-f]{2}\b`, flags: 'gi',
    sample: 'eth0 3c:22:fb:1a:9e:01, wlan0 3C-22-FB-1A-9E-02' },

  { group: 'Dates & times', name: 'Date YYYY-MM-DD', pattern: String.raw`(?<year>\d{4})-(?<month>0[1-9]|1[0-2])-(?<day>0[1-9]|[12]\d|3[01])`, flags: 'g',
    sample: 'Created 2024-03-15, updated 2025-11-02.\nNot dates: 2024-13-01, 2024-02-32' },
  { group: 'Dates & times', name: 'Date DD/MM/YYYY', pattern: String.raw`\b(0?[1-9]|[12]\d|3[01])\/(0?[1-9]|1[0-2])\/(\d{4})\b`, flags: 'g',
    sample: 'Due 15/03/2024 or 1/2/2025. Not: 32/01/2024' },
  { group: 'Dates & times', name: 'Time 24h HH:MM(:SS)', pattern: String.raw`\b([01]?\d|2[0-3]):([0-5]\d)(?::([0-5]\d))?\b`, flags: 'g',
    sample: 'Opens 09:00, closes 17:30:15. Not: 24:00, 12:60' },
  { group: 'Dates & times', name: 'ISO 8601 date-time', pattern: String.raw`\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:?\d{2})?`, flags: 'g',
    sample: 'Logged at 2025-06-01T14:03:22.511Z and 2025-06-01T16:03+02:00' },

  { group: 'Text', name: 'Duplicate words', pattern: String.raw`\b(\w+)\s+\1\b`, flags: 'gi',
    sample: 'This is is a test of the the duplicate finder. Paris in the the spring.' },
  { group: 'Text', name: 'Trailing whitespace', pattern: String.raw`[ \t]+$`, flags: 'gm',
    sample: 'line with spaces   \nclean line\ntab at end\t' },
  { group: 'Text', name: 'Blank lines', pattern: String.raw`^\s*$\n?`, flags: 'gm',
    sample: 'one\n\ntwo\n   \nthree' },
  { group: 'Text', name: 'Words in quotes', pattern: String.raw`(["'])(?:(?!\1).)*\1`, flags: 'g',
    sample: `She said "hello" and then 'goodbye'. A "mismatched' one.` },
  { group: 'Text', name: 'Emoji', pattern: String.raw`\p{Extended_Pictographic}(?:‍\p{Extended_Pictographic})*`, flags: 'gu',
    sample: 'Ship it 🚀, coffee ☕ and a family 👨‍👩‍👧.' },

  { group: 'Validation', name: 'Username (3–16 chars)', pattern: String.raw`^[a-z][\w.-]{2,15}$`, flags: 'gim',
    sample: 'ada_l\nx\n9lives\ngrace.hopper-1906' },
  { group: 'Validation', name: 'Strong password', pattern: String.raw`^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\w\s]).{12,}$`, flags: 'gm',
    sample: 'Tr1cky!Passw0rd\npassword123\nSHORT1!a\ncorrect horse battery staple' },
];
